markdown: kramdown
url: ''
baseurl: null
title: Naurk
description: #Portfolio
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: 'null'
heroimage: /assets/images/hero-image.jpg
email: neonaurk@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
github_username: /
youtube_channel_id: UCP7esidmO2RE-Bp4PpUSDXg
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: /
disqus-shortname: /
author-name: /
author-image: >-
  https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-about: >-
  Sa sa, prova, sa sa.
author-url: /
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-polyglot
permalink: 'blog/:lang/:title/'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
languages: ["en", "it"]  # Elenco delle lingue che vuoi supportare
default_lang: "en"       # Lingua predefinita del sito
exclude_from_localization: ["assets"]
parallel_localization: true
