markdown: kramdown
url: ''
baseurl: null
title: Naurk
description: Cave
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: 'null'
heroimage: /assets/images/bg_img_01.png
email: neonaurk@gmail.com
facebook_username: /
twitter_username: naurk_dev
instagram_username: neonaurk
linkedin_username: /
github_username: Naurk
youtube_channel_id: UCP7esidmO2RE-Bp4PpUSDXg
flickr_username: naurk
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: /
disqus-shortname: /
author-name: /
author-image: >-
  https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-about: >- |
 Sono Norberto, attualmente sto facendo un dottorato in filosofia sull'agency morale e i sistemi di intelligenza artificiale, 
 ma i miei interessi filosofici spaziano dal comportamento dei sistemi naturali e artificiali alla filosofia della biologia e delle menti animali, fino alla simulazione e alla robotica.
 Oltre alla teoria, produco e sviluppo materiale di vario genere, come videogiochi, video, fotografia e musica. Potete trovare maggiori informazioni nelle sezioni progetti, blog e contatti. Grazie dell'attenzione!
 
 I needed a place to gather materials, projects, and digital fragments in one spot, so I created this site. The idea is to create a hybrid between a portfolio page and a blog. I’m not sure if it will work, but I’m experimenting with various formats, and the site is constantly and heavily evolving.
 You can find the source code on my GitHub page; it’s a fork with more information provided at the bottom of the site.
 I’m Norberto, currently pursuing a Ph.D. in philosophy on moral agency and artificial intelligence systems. My philosophical interests range from the behavior of natural and artificial systems to the philosophy of biology and animal minds, as well as simulation and robotics.
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
