markdown: kramdown
url: ''
baseurl: null
title: Naurk
description: Cave
site-image: /WhatATheme/assets/images/meta.jpg
site-keywords: 'Site, Template, Theme'
favicon-url: 'null'
heroimage: /assets/images/hero-image.jpg
email: neonaurk@gmail.com
facebook_username: /
twitter_username: naurk_dev
instagram_username: neonaurk
linkedin_username: /
github_username: Naurk
youtube_channel_id: UCP7esidmO2RE-Bp4PpUSDXg
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
google-analytics: /
disqus-shortname: /
author-name: /
author-image: >-
  https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
author-about: >-
 Welcome to my personal digital den, where I share reflections, research, and projects. 
 I am Norberto, currently a PhD student in Philosophy at the FINO consortium based at the University of Turin. 
 My doctoral work focuses on the meta-ethical aspects of agency in artificial intelligence, but my philosophical interests range from the behavior of 
 natural and artificial systems to the philosophy of biology and animal minds, as well as simulation and robotics. I have worked both as a programmer 
 and a theorist on these topics, collaborating with the Luciano Gallino Laboratory and the LIFE Laboratory at the University of Turin. To learn more 
 about my interests and projects—academic and otherwise—you can check out my blog, projects, or contact sections.
author-url: /
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
